(require 'diminish)

(diminish 'projectile-mode)
(diminish 'company-mode)
(diminish 'editorconfig-mode)
(diminish 'flycheck-mode)
(diminish 'eldoc-mode)
(diminish 'helm-mode)
(diminish 'smartparens-mode)
(diminish 'ruby-end-mode)
